import type { GameId } from './analytics'
export type GameEntry = { id: GameId; name: string; hint: string; seconds: number; color: string; icon: string; controls: string; steps: string[]; mission: string; tag: string }
export const gameList: GameEntry[] = [
  { id: 'planetpost', steps: ["Tap a pipe to turn it.", "Make a path from Start to Planet.", "Tap Send mail when the path is ready."], name: 'Planet Post', hint: 'Connect pipes to deliver mail.', seconds: 180, color: 'purple', icon: 'planet', controls: 'Tap a pipe to turn it. To swap two pipes, drag one onto the other, or choose Swap and tap both. Connect Start to Planet, then tap Send mail. Use Tab and Enter or Space on a keyboard.', mission: 'Connect Start to Planet, then send the mail.', tag: 'Up to 3 min' },
  { id: 'colors', steps: ["Look at the color you need to make.", "Tap the paints to mix your color.", "When the colors match, tap Save color."], name: 'Color Lab', hint: 'Mix paint to match colors.', seconds: 180, color: 'mint', icon: 'water', controls: 'Tap paint to add one drop. Make the color shown above, then tap Save color. Undo removes your last drop. Show recipe tells you which paints to use.', mission: 'Mix paint to make 3 colors.', tag: 'Up to 3 min' },
  { id: 'pebbles', steps: ["Tap a jar to pick its top pebble.", "Move it to an empty jar or onto the same shape.", "Put all pebbles with the same shape together."], name: 'Pebble Sort', hint: 'Sort shapes into jars.', seconds: 180, color: 'blue', icon: 'squares', controls: 'Tap a jar, then another to move the top pebble. It can go into an empty jar or onto the same shape. Each jar holds 3 pebbles.', mission: 'Put all pebbles with the same shape in one jar.', tag: 'Up to 3 min' },
  { id: 'robot', steps: ["Tap arrows to make a path for the robot.", "Collect all 3 stars on your path.", "Finish at the house. Tap Run route to try it."], name: 'Robot Route', hint: 'Collect stars. Get the robot home.', seconds: 180, color: 'purple', icon: 'robot', controls: 'Add arrows to make a path. Each arrow moves one space. Tap an arrow in your path to remove it, then tap Run route to move the robot. You can also use the arrow keys or W A S D.', mission: 'Help the robot collect 3 stars and get home.', tag: 'Up to 3 min' },
  { id: 'bubbles', steps: ["Tap any bubble to pop it.", "Find a friend inside each bubble.", "Pop all 12, then tap All done."], name: 'Bubble Pop', hint: 'Pop bubbles. Find friends.', seconds: 120, color: 'mint', icon: 'sparkle', controls: 'Tap any bubble. On a keyboard, use Tab and Enter or Space.', mission: 'Pop all 12 bubbles.', tag: 'Up to 2 min' },
  { id: 'sky', steps: ["Tap Left or Right to move.", "Collect the yellow gems.", "Tap Jump to go over blocks."], name: 'Sky Dash', hint: 'Jump and collect gems.', seconds: 75, color: 'mint', icon: 'planet', controls: 'Tap Left or Right to steer and Jump to hop. On a keyboard, use ← → or A / D to steer, and Space or ↑ to jump.', mission: 'Collect gems and avoid blocks. Bumps won’t end the game.', tag: '75 seconds' },
  { id: 'matching', steps: ["Tap a card to see its picture.", "Tap another card. Look for the same picture.", "Find all the cards with the same picture."], name: 'Match Club', hint: 'Find two cards with the same picture.', seconds: 180, color: 'pink', icon: 'cards', controls: 'Tap two cards. Find the same picture on both. Different pictures turn back over so you can try again.', mission: 'Find two cards with the same picture. Two matching cards make a pair.', tag: 'Up to 3 min' },
  { id: 'postcards', steps: ["Look at the small picture.", "Tap a piece below the big picture.", "Tap the space where your piece belongs."], name: 'Puzzle Postcards', hint: 'Put the picture together.', seconds: 180, color: 'blue', icon: 'puzzle', controls: 'Tap a piece, then its space in the picture. Tap Show me where for a hint.', mission: 'Put the pieces together to make a picture.', tag: 'Up to 3 min' },
  { id: 'garden', steps: ["Tap the flower you want to grow.", "Tap Water my seed, then Add sunshine.", "Tap Next flower to grow another one."], name: 'Pocket Garden', hint: 'Grow 3 flowers.', seconds: 120, color: 'mint', icon: 'leaf', controls: 'Choose a flower, tap Water my seed, then Add sunshine.', mission: 'Plant, water, and grow 3 flowers.', tag: 'Up to 2 min' },
]
