import type { GameId } from './analytics'
import type { CreatureKind } from './creatures'
export type Category = 'All games' | '3D adventures' | 'Brain teasers' | 'Chill zone' | 'Play together'
export type GameEntry = { id: GameId; name: string; hint: string; category: Category; seconds: number; color: string; icon: string; face: CreatureKind; accent: string; controls: string; mission: string; tag: string }
export const gameList: GameEntry[] = [
  { id: 'bubbles', name: 'Bubble Pop', hint: 'Pop a bubble. Find a happy little friend.', category: 'Chill zone', seconds: 120, color: 'mint', icon: 'sparkle', face: 'bunny', accent: 'teal', controls: 'Tap any bubble. On a keyboard, press Tab and Enter or Space.', mission: 'Twelve bubbles. Twelve little friends. Tap each bubble to see who is hiding inside!', tag: 'Up to 2 min' },
  { id: 'sky', name: 'Sky Dash', hint: 'Catch a little air. Collect a lot of gems.', category: '3D adventures', seconds: 75, color: 'mint', icon: 'planet', face: 'dino', accent: 'teal', controls: 'Use ← → or A / D to steer. Space or ↑ to jump. On a phone, tap the big controls.', mission: 'Ride the floating track, collect gold gems, and steer around coral blocks. Bumps never end your ride.', tag: '75 sec ride' },
  { id: 'maze', name: 'Maze Quest', hint: 'Help your explorer reach the flag.', category: 'Brain teasers', seconds: 180, color: 'purple', icon: 'path', face: 'dino', accent: 'violet', controls: 'Use arrow keys, W A S D, the direction buttons, or swipe one step at a time.', mission: 'Find the flag through a fresh maze. Walls are solid. A hint shows your next step whenever you need it.', tag: 'Up to 3 min' },
  { id: 'matching', name: 'Match Club', hint: 'Flip two cards. Find the matching pictures.', category: 'Brain teasers', seconds: 180, color: 'pink', icon: 'cards', face: 'bunny', accent: 'pink', controls: 'Tap or select two cards. A non-match turns back over after a moment.', mission: 'Find the matching pictures. Start with three pairs, or try six when you feel ready.', tag: 'Up to 3 min' },
  { id: 'tictactoe', name: 'Three in a Row', hint: 'You, a friend, and a little friendly rivalry.', category: 'Play together', seconds: 120, color: 'orange', icon: 'grid', face: 'star', accent: 'amber', controls: 'Tap an empty square. You are X. Get three in a row, column, or diagonal.', mission: 'Play against the app, or pass the device to someone beside you. A single board makes a complete round.', tag: 'Up to 2 min' },
  { id: 'postcards', name: 'Puzzle Postcards', hint: 'Piece together a tiny happy world.', category: 'Brain teasers', seconds: 180, color: 'blue', icon: 'puzzle', face: 'duck', accent: 'blue', controls: 'Pick a piece, then tap a space in your postcard. Show me where gives you a hint. No dragging needed.', mission: 'Choose a picture and put its pieces together. Keep the little reference picture beside you. Every piece has a home.', tag: 'Up to 3 min' },
  { id: 'garden', name: 'Pocket Garden', hint: 'A seed, a splash, a little sunshine.', category: 'Chill zone', seconds: 120, color: 'mint', icon: 'leaf', face: 'cat', accent: 'teal', controls: 'Choose a flower, tap Water my seed, then Add sunshine. Grow three flowers.', mission: 'Make a tiny garden, one flower at a time. Every choice works. Your flowers wait for you between each step.', tag: 'Up to 2 min' },
  { id: 'cafe', name: 'Critter Café', hint: 'Match snacks to six hungry little friends.', category: 'Chill zone', seconds: 120, color: 'yellow', icon: 'heart', face: 'bear', accent: 'amber', controls: 'Look at the snack picture, then tap the matching food button.', mission: 'Serve six friendly customers. There are no wrong orders — the café will give you another try.', tag: 'Up to 2 min' },
  { id: 'studio', name: 'Silly Studio', hint: 'Dress up a friend and make a tiny portrait.', category: 'Chill zone', seconds: 120, color: 'purple', icon: 'sparkle', face: 'bunny', accent: 'violet', controls: 'Choose a friend, a hat, and a place. Every choice works.', mission: 'Make one one-of-a-kind portrait. Change anything you like before you say all done.', tag: 'Up to 2 min' },
]
export const categories: Category[] = ['All games', '3D adventures', 'Brain teasers', 'Chill zone', 'Play together']
