import { useCallback, useEffect, useRef, useState, type ComponentType, type ReactNode } from 'react'
import { type GameEntry } from './gameList'
import { Icon } from './Icons'
import { Maze } from './games/Maze'
import { Matching } from './games/Matching'
import { TicTacToe } from './games/TicTacToe'
import { PocketGarden } from './games/PocketGarden'
import { PuzzlePostcards } from './games/PuzzlePostcards'
import { PostcardArt, postcardScenes, type PostcardScene, type PieceCount } from './games/postcardArt'
import { GardenArt } from './games/gardenArt'
import { Bubbles } from './games/Bubbles'
import { CritterCafe } from './games/CritterCafe'
import { SillyStudio } from './games/SillyStudio'
import { BubbleArt } from './BubbleArt'
import { CafeCover, StudioPortrait } from './games/playfulArt'
import { RoundPace } from './RoundPace'
import { GameContext } from './useGame'
import { RoundClock } from './roundClock'
import { recordStart, recordFinish, recordTime } from './analytics'
import { setAudioPaused } from './sound'

type Phase='intro'|'playing'|'paused'|'done'
export function GameSession({ game, quiet, onBack, onLeave, overlayOpen=false }: {game: GameEntry; quiet: boolean; onLeave:()=>void; onBack:()=>void;overlayOpen?:boolean}) {
  const [phase,setPhase]=useState<Phase>('intro'),[seconds,setSeconds]=useState(game.seconds),[message,setMessage]=useState(''),[round,setRound]=useState(0)
  const [ThreeGame,setThreeGame]=useState<ComponentType<{kind:'sky'}>|null>(null),[loadError,setLoadError]=useState(false)
  const livePhase=useRef<Phase>('intro'),clock=useRef(new RoundClock(game.seconds*1000)),finished=useRef(false),countedTime=useRef(0),focusRef=useRef<HTMLDivElement>(null)
  const [matchingPairs,setMatchingPairs]=useState<3|6>(3)
  const [relaxed,setRelaxed]=useState(game.id!=='sky')
  const [postcardScene,setPostcardScene]=useState<PostcardScene>('Ocean hello')
  const [postcardPieces,setPostcardPieces]=useState<PieceCount>(4)
  const resumeTarget=useRef<HTMLElement|null>(null)
  const canRelax=game.id!=='sky'
  const [artwork,setArtwork]=useState<ReactNode>(null)
  const summary=useRef('')
  const report=useCallback((text:string)=>{summary.current=text},[])
  const is3D=game.id==='sky'
  const changePhase=useCallback((next:Phase)=>{livePhase.current=next;setPhase(next)},[])
  const flush=useCallback(()=>{const delta=clock.current.elapsed-countedTime.current;if(delta>=1000){recordTime(game.id,delta/1000);countedTime.current=clock.current.elapsed}},[game.id])
  const finish=useCallback((text?:string,art?:ReactNode)=>{if(finished.current||livePhase.current==='intro'||livePhase.current==='done')return;clock.current.pause(performance.now());finished.current=true;setArtwork(art??null);setMessage(text||'A little adventure, complete.');changePhase('done');recordFinish(game.id);flush()},[changePhase,flush,game.id])
  useEffect(()=>{if(!is3D)return;let cancelled=false;import('./games/ThreeGames').then(module=>{if(!cancelled)setThreeGame(()=>module.ThreeGame)}).catch(()=>{if(!cancelled)setLoadError(true)});return()=>{cancelled=true}},[is3D])
  useEffect(()=>{setAudioPaused(phase!=='playing');return()=>setAudioPaused(true)},[phase])
  useEffect(()=>{if(phase!=='playing')return;clock.current.resume(performance.now());const tick=()=>{const elapsed=clock.current.tick(performance.now());if(Number.isFinite(clock.current.limit))setSeconds(Math.max(0,Math.ceil((clock.current.limit-elapsed)/1000)));if(clock.current.done)finish(game.id==='sky'?'You landed. Nice ride.':'That’s a wrap. Thanks for playing.')};const interval=setInterval(tick,100);return()=>{clearInterval(interval);clock.current.pause(performance.now());flush()}},[phase,finish,flush,game.id])
  const pause=useCallback(()=>{if(livePhase.current==='playing'){clock.current.pause(performance.now());changePhase('paused')}},[changePhase])
  useEffect(()=>{if(overlayOpen)pause()},[overlayOpen,pause])
  useEffect(()=>{const hidden=()=>{if(document.hidden)pause()};const key=(e:KeyboardEvent)=>{if(e.key==='Escape'&&livePhase.current==='playing'&&!(e.target instanceof Element&&e.target.closest('dialog'))){e.preventDefault();pause()}};window.addEventListener('blur',pause);document.addEventListener('visibilitychange',hidden);window.addEventListener('keydown',key);window.addEventListener('pagehide',pause);return()=>{window.removeEventListener('blur',pause);document.removeEventListener('visibilitychange',hidden);window.removeEventListener('keydown',key);window.removeEventListener('pagehide',pause);clock.current.pause(performance.now());flush()}},[pause,flush])
  useEffect(()=>{if(overlayOpen)return;if(phase!=='playing')focusRef.current?.focus({preventScroll:true});else {const el=document.querySelector<HTMLElement>('.game-surface [tabindex="0"], .game-surface button:not(:disabled):not([aria-disabled="true"])');const previous=resumeTarget.current;resumeTarget.current=null;if(previous?.isConnected&&!previous.matches(':disabled,[aria-disabled="true"]'))previous.focus();else el?.focus()}},[phase,overlayOpen])
  const start=()=>{window.scrollTo(0,0);finished.current=false;setArtwork(null);clock.current=new RoundClock(relaxed?Infinity:game.seconds*1000);countedTime.current=0;setSeconds(game.seconds);setMessage('');summary.current='';recordStart(game.id);changePhase('playing')}
  const prepareAgain=()=>{setRound(n=>n+1);changePhase('intro')}
  const activeGame=()=>{switch(game.id){case'bubbles':return <Bubbles/>;case'maze':return <Maze onFinish={()=>finish('You found your way. Quest complete.')}/>;case'matching':return <Matching pairs={matchingPairs} onFinish={()=>finish(matchingPairs===3?'All three pairs. A perfect match.':'All six pairs. A perfect match.')}/>;case'tictactoe':return <TicTacToe onFinish={()=>finish()}/>;case'postcards':return <PuzzlePostcards scene={postcardScene} count={postcardPieces}/>;case'garden':return <PocketGarden/>;case'cafe':return <CritterCafe/>;case'studio':return <SillyStudio/>;case'sky':return ThreeGame?<ThreeGame kind="sky"/>:null}}
  return <section className={`session theme-${game.color} ${is3D ? "adventure-session" : ""}`} data-game={game.id}>
    <div className="session-heading"><button className="text-button" onClick={onBack}><Icon name="back"/> All games</button><div><h1>{game.name}</h1><span>{game.category}</span></div><button hidden={phase!=="playing"} className="secondary-button pause-button" onClick={pause} disabled={phase!=='playing'}><Icon name="pause"/> Pause</button></div>
    {phase==='intro'?<div className="round-intro" ref={focusRef} tabIndex={-1}>{is3D?<img className="intro-art" src={`/art/${game.id}.webp`} alt=""/>:game.id==='bubbles'?<div className="intro-bubbles"><BubbleArt/></div>:game.id==='cafe'?<div className="intro-picture"><CafeCover/></div>:game.id==='studio'?<div className="intro-picture"><StudioPortrait/></div>:game.id==='garden'?<div className="intro-picture"><GardenArt/></div>:game.id==='postcards'?<div className="intro-picture"><PostcardArt scene={postcardScene}/></div>:<span className="intro-icon"><Icon name={game.icon} size={70}/></span>}<div className="intro-copy"><h2>{game.id==='sky'?'Ready for a little airtime?':game.id==='bubbles'?'Ready, set… pop!':game.id==='matching'?'Let’s find a pair.':game.id==='cafe'?'Welcome to the café!':game.id==='studio'?'Let’s make something silly!':game.id==='garden'?'Let’s grow something happy.':game.id==='postcards'?'Make a little world.':'A little challenge, your way.'}</h2><p>{game.mission}</p><details className="intro-help"><summary><Icon name="info" size={18}/> How to play</summary><p>{game.controls}</p></details>{game.id==='postcards'&&<div className="postcard-setup"><fieldset><legend>Choose your picture</legend><div className="postcard-scenes">{postcardScenes.map(scene=><button key={scene} aria-pressed={postcardScene===scene} onClick={()=>setPostcardScene(scene)}><PostcardArt scene={scene} decorative/><span>{scene}{postcardScene===scene&&<Icon name="check" size={16}/>}</span></button>)}</div></fieldset><fieldset className="matching-level"><legend>Choose your puzzle</legend><div>{([4,6] as const).map(count=><button key={count} aria-pressed={postcardPieces===count} onClick={()=>setPostcardPieces(count)}><Icon name="puzzle"/><span><strong>{count===4?'Little puzzle':'Bigger puzzle'}</strong><small>{count} pieces</small></span>{postcardPieces===count&&<Icon name="check" size={18}/>}</button>)}</div></fieldset></div>}{canRelax&&<RoundPace relaxed={relaxed} onChange={setRelaxed} duration={game.tag}/>}{game.id==='matching'&&<fieldset className="matching-level"><legend>Choose your board</legend><div>{([3,6] as const).map(pairs=><button key={pairs} aria-pressed={matchingPairs===pairs} onClick={()=>setMatchingPairs(pairs)}><Icon name={pairs===3?'heart':'sparkle'}/><span><strong>{pairs===3?'Little match':'Big match'}</strong><small>{pairs} pairs</small></span>{matchingPairs===pairs&&<Icon name="check" size={18}/>}</button>)}</div></fieldset>}<button className="primary-button" onClick={start} disabled={is3D&&!ThreeGame}><Icon name="play" weight="fill"/>{is3D&&!ThreeGame?loadError?'Adventure couldn’t load':'Getting your adventure ready…':'Start playing'}</button>{loadError&&<p role="alert">This 3D adventure couldn’t load. Go back and try one of the puzzles.</p>}<p className="intro-footnote"><Icon name="wave" size={16}/> Name called? You can leave anytime.</p></div></div>
    :phase==='done'?<div className="round-result" tabIndex={-1} ref={focusRef}>{artwork?<div className="result-art">{artwork}</div>:<div className="result-icon"><Icon name="check" size={60}/></div>}<h2>{message}</h2>{summary.current&&<strong className="result-summary">{summary.current}</strong>}<p>A good moment to look up and check for your name.</p><div className="result-actions"><button className="primary-button" onClick={onLeave}><Icon name="wave"/> I’m heading out</button><button className="secondary-button" onClick={onBack}>All games <Icon name="right"/></button></div><button className="text-button" onClick={prepareAgain}>Still waiting? Set up another round</button></div>
    :<GameContext.Provider value={{paused:phase!=='playing',quiet,relaxed,finish,report}}><div className={`play-shell ${phase==='paused'?'is-paused':''}`}><div className="round-bar"><span><Icon name={game.icon}/> One little adventure</span>{relaxed?<span className="relaxed-label"><Icon name="leaf" size={18}/> Your own pace</span>:<span className="round-time" role="timer" aria-live="off" aria-label={`${seconds} seconds remaining`}><Icon name="clock" size={18}/>{Math.floor(seconds/60)}:{String(seconds%60).padStart(2,'0')}</span>}</div>{!relaxed&&<div className="round-progress" role="progressbar" aria-label="Round time remaining" aria-valuemin={0} aria-valuemax={game.seconds} aria-valuenow={seconds}><span style={{width:`${seconds/game.seconds*100}%`}}/></div>}<div className="game-surface" key={round} inert={phase==='paused'} onFocusCapture={event=>{resumeTarget.current=event.target as HTMLElement}}>{activeGame()}</div>{phase==='paused'&&<div className="pause-overlay" ref={focusRef} tabIndex={-1} role="region" aria-label="Game paused"><span className="pause-icon"><Icon name="pause" size={44}/></span><h2>Take your time.</h2><p>{relaxed?'Your game is saved right here.':'Your game and its clock are paused.'}</p><div className="pause-instructions"><strong>How to play {game.name}</strong><p>{game.controls}</p></div><button className="primary-button" onClick={()=>changePhase('playing')}><Icon name="play" weight="fill"/> Keep playing</button><button className="secondary-button" onClick={onLeave}><Icon name="wave"/> My appointment</button></div>}</div><div className="session-tools"><button className="secondary-button" onClick={pause}><Icon name="info"/> How to play</button>{relaxed&&<button className="secondary-button" onClick={()=>finish('A lovely play break. Thanks for joining in!')}><Icon name="check"/> Finish this round</button>}</div><p className="session-reminder"><Icon name="wave" size={18}/> Name called? Tap <button onClick={onLeave}>My appointment</button> to stop right away.</p></GameContext.Provider>}
  </section>
}
