import { test, expect } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'

test('start is visible before optional setup and replay creates a fresh round', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Play Bubble Pop', exact: true }).click()
  await expect(page.locator('.game-options')).not.toHaveAttribute('open', '')
  await expect(page.getByRole('button', { name: 'Start playing', exact: true })).toBeInViewport()
  await page.getByRole('button', { name: 'Start playing', exact: true }).click()
  for (let i = 1; i <= 12; i++) await page.getByRole('button', { name: `Pop bubble ${i}`, exact: true }).click()
  await page.getByRole('button', { name: 'All done', exact: true }).click()
  await page.getByRole('button', { name: 'Play again', exact: true }).click()
  await expect(page.locator('.bubble-count')).toHaveText('0 / 12')
  await expect(page.getByRole('button', { name: 'Pop bubble 1', exact: true })).toBeFocused()
  const stats = await page.evaluate(() => JSON.parse(localStorage.getItem('mvp.pilot.v1')!).games.bubbles)
  expect(stats.starts).toBe(2); expect(stats.finishes).toBe(1)
})

test('featured navigation returns to its original control and Home clears a filter', async ({ page }) => {
  await page.goto('/')
  await page.locator('#quick-bubbles').click()
  await page.getByRole('button', { name: 'All games', exact: true }).click()
  await expect(page.locator('#quick-bubbles')).toBeFocused()
  await page.getByRole('button', { name: 'Chill zone', exact: true }).click()
  await page.getByRole('button', { name: 'Patient Playroom home', exact: true }).click()
  await expect(page.getByRole('button', { name: 'All games', exact: true })).toHaveAttribute('aria-pressed', 'true')
})

test('solid backgrounds persist and settings preserve the paused game', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Play Pocket Garden', exact: true }).click()
  await page.getByRole('button', { name: 'Start playing', exact: true }).click()
  await page.getByRole('button', { name: 'Daisy', exact: true }).click()
  await page.getByRole('button', { name: 'Play settings', exact: true }).click()
  await page.getByRole('switch', { name: 'Solid backgrounds', exact: true }).click()
  await expect(page.locator('html')).toHaveAttribute('data-solid', 'true')
  expect(await page.locator('.app-header').evaluate(el => getComputedStyle(el).backdropFilter)).toBe('none')
  expect((await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa', 'wcag22aa']).analyze()).violations).toEqual([])
  await page.getByRole('button', { name: 'Done', exact: true }).click()
  await expect(page.getByRole('region', { name: 'Game paused' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Finish this round', exact: true })).not.toBeVisible()
  await page.getByRole('button', { name: 'Keep playing', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Water my seed', exact: true })).toBeVisible()
  await page.reload()
  await expect(page.locator('html')).toHaveAttribute('data-solid', 'true')
})

test('system font is consistent and glass becomes opaque for increased contrast', async ({ page }) => {
  await page.goto('/')
  const fonts = await page.locator('body,h1,.category').evaluateAll(nodes => nodes.map(el => getComputedStyle(el).fontFamily))
  expect(fonts.every(font => font.includes('-apple-system') && !font.includes('Fredoka'))).toBe(true)
  await page.emulateMedia({ contrast: 'more', reducedMotion: 'reduce' })
  expect(await page.locator('.app-header').evaluate(el => getComputedStyle(el).backdropFilter)).toBe('none')
  await page.setViewportSize({ width: 320, height: 800 })
  await page.evaluate(() => { document.documentElement.style.fontSize = '200%' })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.getByRole('button', { name: 'Play Puzzle Postcards', exact: true }).click()
  await page.locator('.game-options > summary').click()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('changing options opens setup, preserves choices, and starts a new round', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Play Match Club', exact: true }).click()
  await page.locator('.game-options > summary').click()
  await page.getByRole('button', { name: 'Big match 6 pairs', exact: true }).click()
  expect((await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa', 'wcag22aa']).analyze()).violations).toEqual([])
  await page.getByRole('button', { name: 'Start playing', exact: true }).click()
  await page.getByRole('button', { name: 'Finish this round', exact: true }).click()
  await page.getByRole('button', { name: 'Change game options', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Big match 6 pairs', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await page.getByRole('button', { name: 'Little match 3 pairs', exact: true }).click()
  await page.getByRole('button', { name: 'Start playing', exact: true }).click()
  await expect(page.locator('.memory-card')).toHaveCount(6)
})
