import {test,expect,type Page} from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'
import fs from 'node:fs/promises'
const games=[['sky','Sky Dash',75],['orbit','Orbit Pop',60],['maze','Maze Quest',180],['matching','Match Club',180],['merge','Merge 128',180],['tictactoe','Three in a Row',120],['words','Word Scout',180],['ispy','Hidden Friends',120],['explore','Room Explorer',120],['dance','Beat Garden',60]]as const
async function start(page:Page,name:string){await page.getByRole('button',{name:`Play ${name}`,exact:true}).click();await page.getByRole('button',{name:'Start playing',exact:true}).click();await expect(page.locator('.game-surface')).toBeVisible()}
async function stats(page:Page,id:string){return page.evaluate(id=>JSON.parse(localStorage.getItem('mvp.pilot.v1')||'{}').games?.[id],id)}
test.beforeEach(async({page})=>{await page.goto('/')})
test('all game screens have accessible controls and no browser runtime errors',async({page})=>{
  test.setTimeout(90000);const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message))
  for(const[,name]of games){await start(page,name);const results=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();expect(results.violations,`${name} accessibility`).toEqual([]);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`${name} overflow`).toBe(true);await page.getByRole('button',{name:'All games',exact:true}).click()}
  expect(errors).toEqual([])
})
test('staff panel pauses play, traps focus, and closes with Escape',async({page})=>{await start(page,'Maze Quest');await page.getByRole('button',{name:'Pilot data',exact:true}).click();await expect(page.getByRole('dialog',{name:'Pilot data'})).toBeVisible();await expect(page.getByRole('region',{name:'Game paused',includeHidden:true})).toHaveCount(1);await page.keyboard.press('Escape');await expect(page.getByRole('dialog',{name:'Pilot data'})).toHaveCount(0);await expect(page.getByRole('region',{name:'Game paused'})).toBeVisible()})
test('narrow phone and zoomed text stay usable',async({page})=>{await page.setViewportSize({width:320,height:800});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await start(page,'Merge 128');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);await page.getByRole('button',{name:'All games',exact:true}).click();await page.evaluate(()=>document.documentElement.style.fontSize='200%');expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)})

test('library, categories, silence, artwork and responsive layout',async({page},info)=>{
  await expect(page).toHaveTitle(/Patient Playroom/);await expect(page.getByRole('button',{name:'Turn sound on'})).toBeVisible();await expect(page.locator('.game-card')).toHaveCount(10)
  await page.getByRole('button',{name:'3D adventures',exact:true}).click();await expect(page.locator('.game-card')).toHaveCount(2)
  await page.getByRole('button',{name:'Chill zone',exact:true}).click();await expect(page.locator('.game-card')).toHaveCount(3)
  await page.getByRole('button',{name:'All games',exact:true}).click()
  await page.evaluate(()=>document.fonts.ready);await expect.poll(()=>page.locator('img').evaluateAll(imgs=>imgs.every(img=>(img as HTMLImageElement).complete&&(img as HTMLImageElement).naturalWidth>0))).toBe(true)
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
  const a11y=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();expect(a11y.violations).toEqual([])
  await fs.mkdir('artifacts',{recursive:true});await page.screenshot({path:`artifacts/${info.project.name}-library.png`,fullPage:true})
})
for(const[id,name,seconds]of games){test(`${name}: start, pause, resume, bounded round, no auto replay`,async({page})=>{
  await page.clock.install();await page.reload();await start(page,name)
  await page.clock.fastForward(5000);await page.getByRole('button',{name:'Pause',exact:true}).click();await expect(page.getByRole('region',{name:'Game paused'})).toBeVisible();const before=await page.locator('.round-time').textContent()
  await page.clock.fastForward(30000);expect(await page.locator('.round-time').textContent()).toBe(before);await expect(page.locator('.game-surface')).toHaveAttribute('inert','')
  await page.getByRole('button',{name:'Keep playing'}).click();await page.clock.fastForward((seconds+1)*1000);await expect(page.locator('.round-result')).toBeVisible();await expect(page.getByRole('button',{name:'Start playing',exact:true})).toHaveCount(0);expect((await stats(page,id)).finishes).toBe(1)
  await page.clock.fastForward(180000);expect((await stats(page,id)).finishes).toBe(1);await expect(page.locator('.game-surface')).toHaveCount(0)
})}
test('appointment exits immediately, cuts sound, and does not count completion',async({page})=>{
  await page.getByRole('button',{name:'Turn sound on'}).click();await start(page,'Sky Dash');await page.getByRole('button',{name:'My appointment',exact:true}).first().click();await expect(page.getByRole('heading',{name:'Go do your thing.'})).toBeVisible();await expect(page.locator('canvas')).toHaveCount(0);await expect(page.getByRole('button',{name:'Turn sound on'})).toBeVisible();expect((await stats(page,'sky')).finishes).toBe(0)
})
test('maze can be solved, cannot walk through a wall, and hints work',async({page},info)=>{
  await start(page,'Maze Quest');const board=page.locator('.maze-board');await board.focus();await page.keyboard.press('ArrowUp');await expect(page.locator('.maze-tile.player')).toHaveAttribute('data-y','1')
  await page.getByRole('button',{name:'Hint',exact:true}).click();await expect(page.locator('.maze-tile.hint')).toHaveCount(1)
  await page.screenshot({path:`artifacts/${info.project.name}-maze.png`,fullPage:true})
  const steps=await board.evaluate(el=>{const open=new Set([...el.querySelectorAll('[data-wall="false"]')].map(n=>`${(n as HTMLElement).dataset.x},${(n as HTMLElement).dataset.y}`));const queue=[{x:1,y:1,path:[]as string[]}],seen=new Set(['1,1']);for(let n=0;n<queue.length;n++){const a=queue[n]!;if(a.x===9&&a.y===9)return a.path;for(const[dx,dy,key]of[[0,-1,'ArrowUp'],[0,1,'ArrowDown'],[-1,0,'ArrowLeft'],[1,0,'ArrowRight']]as const){const x=a.x+dx,y=a.y+dy,k=`${x},${y}`;if(open.has(k)&&!seen.has(k)){seen.add(k);queue.push({x,y,path:[...a.path,key]})}}}throw Error('No path')})
  await board.focus();for(const key of steps)await page.keyboard.press(key);await expect(page.getByRole('heading',{name:'You found your way. Quest complete.'})).toBeVisible();expect((await stats(page,'maze')).finishes).toBe(1)
})
test('memory mismatches lock, pause retains them, and all pairs can be completed',async({page})=>{
  await page.clock.install();await page.reload();await start(page,'Match Club');const cards=page.locator('.memory-card'),known:Record<string,number[]>={}
  for(let i=0;i<12;i+=2){for(const index of [i,i+1]){await cards.nth(index).click();const label=(await cards.nth(index).getAttribute('aria-label'))!;const kind=label.split(': ')[1]!.split(',')[0]!;(known[kind]??=[]).push(index)}if(await cards.nth(i).evaluate(el=>!el.classList.contains('matched'))){await expect(cards.nth((i+2)%12)).toBeDisabled();if(i===0){await page.getByRole('button',{name:'Pause',exact:true}).click();await page.clock.fastForward(2000);await page.getByRole('button',{name:'Keep playing'}).click();await expect(cards.nth(i)).toHaveClass(/open/)}await page.clock.fastForward(950)}}
  for(const indices of Object.values(known)){if(await page.locator('.round-result').count())break;if(await cards.nth(indices[0]!).isEnabled()){await cards.nth(indices[0]!).click();await cards.nth(indices[1]!).click()}}
  await expect(page.getByRole('heading',{name:'All six pairs. A perfect match.'})).toBeVisible();expect((await stats(page,'matching')).finishes).toBe(1)
})
test('tic tac toe two-player win and thinking pauses correctly',async({page})=>{
  await start(page,'Three in a Row');await page.getByRole('button',{name:'Two players',exact:true}).click();for(const i of[0,3,1,4,2])await page.getByRole('button',{name:`Empty square ${i+1}`,exact:true}).click();await expect(page.getByRole('heading',{name:'You made three in a row.'})).toBeVisible();expect((await stats(page,'tictactoe')).finishes).toBe(1)
  await page.getByRole('button',{name:'All games',exact:true}).first().click();await page.clock.install();await page.reload();await start(page,'Three in a Row');await page.getByRole('button',{name:'Empty square 1',exact:true}).click();await page.getByRole('button',{name:'Pause',exact:true}).click();await page.clock.fastForward(2000);await expect(page.locator('.ttt-board button.mark-o')).toHaveCount(0);await page.getByRole('button',{name:'Keep playing'}).click();await page.clock.fastForward(600);await expect(page.locator('.ttt-board button.mark-o')).toHaveCount(1)
})
test('merge supports touch or keyboard moves and exactly restores an undo',async({page},info)=>{
  await start(page,'Merge 128');const before=await page.locator('.merge-tile').allTextContents();for(const d of ['left','down','right']){await page.getByRole('button',{name:`Move ${d}`,exact:true}).click();if((await page.locator('.merge-tile').allTextContents()).join()!==before.join())break}
  expect((await page.locator('.merge-tile').allTextContents()).join()).not.toBe(before.join());await page.getByRole('button',{name:'Undo',exact:true}).click();expect(await page.locator('.merge-tile').allTextContents()).toEqual(before);await expect(page.getByRole('button',{name:'Undo',exact:true})).toBeDisabled();await page.screenshot({path:`artifacts/${info.project.name}-merge.png`,fullPage:true})
})
test('word search supports discovery, hints, reversed endpoints and completion',async({page})=>{
  await start(page,'Word Scout');await page.getByRole('button',{name:'Hint',exact:true}).click();await expect(page.locator('.word-board button.hint')).toHaveCount(1)
  const letters=await page.locator('.word-board button').allTextContents(),words=['MOON','STAR','ORBIT','COMET','MARS'];let reversed=false
  for(const word of words){let pair:number[]|undefined;for(let start=0;start<49&&!pair;start++)for(const[dx,dy]of[[-1,-1],[-1,0],[-1,1],[0,-1],[0,1],[1,-1],[1,0],[1,1]]){const path=Array.from(word,(_,n)=>[start%7+dx!*n,Math.floor(start/7)+dy!*n]);if(path.every(([x,y],n)=>x!>=0&&y!>=0&&x!<7&&y!<7&&letters[y!*7+x!]===word[n])){pair=[start,path.at(-1)![1]!*7+path.at(-1)![0]!];break}}expect(pair).toBeTruthy();if(!reversed){pair!.reverse();reversed=true}await page.locator('.word-board button').nth(pair![0]!).click();await page.locator('.word-board button').nth(pair![1]!).click()}
  await expect(page.getByRole('heading',{name:'Every word found. Stellar spotting.'})).toBeVisible()
})
for(const[name,selector,message]of[['Hidden Friends','.g-spy .g-hotspot','All five friends found. Great eyes.'],['Room Explorer','.g-hotspot','Every friend found. Nice exploring.']]as const)test(`${name}: every friend can be found`,async({page})=>{await start(page,name);const total=await page.locator(selector).count();for(let i=0;i<total;i++)await page.locator(selector).nth(i).click();await expect(page.getByRole('heading',{name:message})).toBeVisible()})
test('beat garden supports keys with a focused pad and without sound',async({page})=>{await start(page,'Beat Garden');await page.getByRole('button',{name:'Play Pop, key 3',exact:true}).click();await page.keyboard.press('1');await page.keyboard.press('2');await expect(page.getByText('3 beats, all yours.',{exact:true})).toBeVisible();await expect(page.getByRole('button',{name:'Turn sound on',exact:true})).toBeVisible()})
test('3D renders, sky steering and jump work, orbit can complete',async({page},info)=>{
  await start(page,'Sky Dash');await expect(page.locator('canvas')).toHaveCount(1);await expect(page.getByText(/3D isn’t available/)).toHaveCount(0);await page.getByRole('button',{name:'Steer right',exact:true}).click();await expect(page.locator('.lane-labels .current')).toHaveText('Right');await page.getByRole('button',{name:'Jump',exact:false}).click();await expect(page.getByRole('button',{name:/Airtime/})).toBeVisible();await page.screenshot({path:`artifacts/${info.project.name}-sky.png`,fullPage:true})
  await page.getByRole('button',{name:'All games',exact:true}).click();await start(page,'Orbit Pop');await expect(page.locator('canvas')).toHaveCount(1);await page.screenshot({path:`artifacts/${info.project.name}-orbit.png`,fullPage:true});for(let i=0;i<18;i++){const target=page.getByRole('button',{name:`Pop planet ${i%6+1}`,exact:true});const box=(await target.boundingBox())!;if(info.project.name==='mobile')await page.touchscreen.tap(box.x+box.width/2,box.y+box.height/2);else await page.mouse.click(box.x+box.width/2,box.y+box.height/2);await page.waitForTimeout(180)}await expect(page.getByRole('heading',{name:'Orbit powered. All 18 planets collected.'})).toBeVisible();expect((await stats(page,'orbit')).finishes).toBe(1)
})
test('flat fallback remains playable when WebGL is unavailable',async({page})=>{await page.addInitScript(()=>{const original=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(type:string,...args:unknown[]){if(type==='webgl2'||type==='webgl'||type==='experimental-webgl')return null;return Reflect.apply(original,this,[type,...args])}as typeof original});await page.reload();await start(page,'Sky Dash');await expect(page.getByText(/same game in flat view/)).toBeVisible();await page.getByRole('button',{name:'Steer left',exact:true}).click();await expect(page.locator('.lane-labels .current')).toHaveText('Left');await page.getByRole('button',{name:'All games',exact:true}).click();await start(page,'Orbit Pop');await expect(page.getByText(/same game in flat view/)).toBeVisible();await page.getByRole('button',{name:'Pop planet 1',exact:true}).click();await expect(page.locator('.three-hud')).toContainText('1 / 18')})
test('hidden-tab pause, reduced motion, storage failure and staff data',async({page})=>{
  await page.emulateMedia({reducedMotion:'reduce'});await page.reload();await expect(page.getByRole('button',{name:'Less motion',exact:true})).toHaveAttribute('aria-pressed','true');await start(page,'Maze Quest');await page.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,get:()=>true});document.dispatchEvent(new Event('visibilitychange'))});await expect(page.getByRole('region',{name:'Game paused'})).toBeVisible();await page.getByRole('button',{name:'My appointment',exact:true}).first().click();await page.getByRole('button',{name:'Back to the playroom',exact:false}).click();await page.getByRole('button',{name:'Pilot data',exact:true}).click();await expect(page.getByRole('dialog',{name:'Pilot data'})).toBeVisible();await page.getByRole('button',{name:'Close',exact:true}).click();await page.addInitScript(()=>{Storage.prototype.setItem=()=>{throw new DOMException('Storage disabled','QuotaExceededError')};Storage.prototype.getItem=()=>{throw new DOMException('Storage disabled','SecurityError')}});await page.reload();await start(page,'Maze Quest');await expect(page.locator('.maze-board')).toBeVisible()
})
