import { test, expect, type Page } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'

async function start(page: Page) {
  await page.goto('/')
  await page.getByRole('button', { name: 'Play Robot Route', exact: true }).click()
  await page.getByRole('button', { name: 'Start playing', exact: true }).click()
}

test('Robot Route is new, featured, and launches the correct game', async ({ page }, info) => {
  await page.goto('/')
  await expect(page.locator('.game-card')).toHaveCount(10)
  await expect(page.locator('.game-card').first()).toHaveAccessibleName('Play Robot Route')
  await expect(page.locator('.feature-robot')).toContainText('New · Featured game')
  await expect.poll(() => page.locator('.feature-robot img').evaluate((img: HTMLImageElement) => img.naturalWidth)).toBeGreaterThan(0)
  await page.screenshot({ path: `artifacts/${info.project.name}-robot-feature.png`, fullPage: true })
  await page.locator('.feature-robot .feature-play').click()
  await expect(page.getByRole('heading', { name: 'Robot Route', exact: true })).toBeVisible()
  expect((await new AxeBuilder({ page }).withTags(['wcag2a','wcag2aa','wcag21aa','wcag22aa']).analyze()).violations).toEqual([])
  await page.getByRole('button', { name: 'All games', exact: true }).click()
  await page.locator('.quick-bubbles').click()
  await expect(page.getByRole('heading', { name: 'Bubble Pop', exact: true })).toBeVisible()
})

test('edit, blocked feedback, hints and a complete animated route work', async ({ page }, info) => {
  await page.clock.install()
  await start(page)
  const workspace = page.getByRole('group', { name: /^Robot Route workspace/ })
  await workspace.focus()
  await page.keyboard.press('ArrowLeft')
  await page.keyboard.press('ArrowRight')
  await expect(page.locator('.robot-queue button')).toHaveCount(2)
  await page.getByRole('button', { name: 'Remove step 2: right', exact: true }).click()
  await page.getByRole('button', { name: 'Run route', exact: true }).click()
  await page.clock.runFor(600)
  await expect(page.getByRole('status')).toContainText('Step 1 goes into a block')
  await expect(page.locator('.robot-board [data-robot]')).toHaveAttribute('data-cell', '20')
  await page.getByRole('button', { name: 'Hint', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('adjusted')
  for (let i = 0; i < 20; i++) await page.getByRole('button', { name: 'Hint', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('Your route is ready!')
  await page.screenshot({ path: `artifacts/${info.project.name}-robot-ready.png`, fullPage: true })
  expect((await new AxeBuilder({ page }).withTags(['wcag2a','wcag2aa','wcag21aa','wcag22aa']).analyze()).violations).toEqual([])
  await page.getByRole('button', { name: 'Run route', exact: true }).click()
  await page.clock.runFor(12000)
  await expect(page.getByRole('heading', { name: 'All stars aboard. Robot home!' })).toBeVisible()
  await expect(page.locator('.result-summary')).toContainText('All 3 stars collected')
  const stats = await page.evaluate(() => JSON.parse(localStorage.getItem('mvp.pilot.v1')!).games.robot)
  expect(stats.finishes).toBe(1)
  await page.clock.runFor(5000)
  await expect(page.locator('.round-result')).toBeVisible()
})

test('test runs pause, stop, restart and exit immediately', async ({ page }) => {
  await page.clock.install({ time: new Date('2026-01-01T00:00:00Z') })
  await page.clock.pauseAt(new Date('2026-01-01T00:00:00Z'))
  await start(page)
  for (let i = 0; i < 6; i++) await page.getByRole('button', { name: 'Hint', exact: true }).click()
  await page.getByRole('button', { name: 'Run route', exact: true }).click()
  await page.clock.runFor(600)
  await expect(page.locator('.robot-queue .executed')).toHaveCount(1)
  await page.getByRole('button', { name: 'Pause', exact: true }).click()
  const before = await page.locator('.robot-board [data-robot]').getAttribute('data-cell')
  await page.clock.runFor(5000)
  await expect(page.locator('.robot-board [data-robot]')).toHaveAttribute('data-cell', before!)
  await page.getByRole('button', { name: 'Keep playing', exact: true }).click()
  await page.clock.runFor(600)
  await expect(page.locator('.robot-queue .executed')).toHaveCount(2)
  await expect(page.locator('.robot-board [data-robot]')).not.toHaveAttribute('data-cell', before!)
  await page.getByRole('button', { name: 'Stop test', exact: true }).click()
  const stopped = await page.locator('.robot-board [data-robot]').getAttribute('data-cell')
  await page.clock.runFor(3000)
  await expect(page.locator('.robot-board [data-robot]')).toHaveAttribute('data-cell', stopped!)
  await page.getByRole('button', { name: 'Run route', exact: true }).click()
  await expect(page.locator('.robot-board [data-robot]')).toHaveAttribute('data-cell', '20')
  await page.getByRole('button', { name: 'My appointment', exact: true }).first().click()
  await page.clock.runFor(12000)
  await expect(page.getByRole('heading', { name: 'Go do your thing.' })).toBeVisible()
  expect(await page.evaluate(() => JSON.parse(localStorage.getItem('mvp.pilot.v1')!).games.robot.finishes)).toBe(0)
})

test('touch, keyboard scope, 320px reflow, enlarged text and reduced motion', async ({ page }, info) => {
  await page.setViewportSize({ width: 320, height: 800 })
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await start(page)
  const add = page.getByRole('button', { name: 'Add up', exact: true })
  if (info.project.name === 'mobile') await add.tap(); else await add.click()
  await expect(page.locator('.robot-queue button')).toHaveCount(1)
  await page.getByRole('button', { name: 'Turn sound on', exact: true }).focus()
  await page.keyboard.press('ArrowRight')
  await expect(page.locator('.robot-queue button')).toHaveCount(1)
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await expect(page.locator('.robot-queue button')).toHaveCount(0)
  for (const size of ['100%', '200%']) {
    await page.evaluate(size => document.documentElement.style.fontSize = size, size)
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  }
  await page.evaluate(() => document.documentElement.style.fontSize = '')
  expect(await page.locator('.robot-here svg').evaluate(el => getComputedStyle(el).animationName)).toBe('none')
  await expect(page.getByRole('button', { name: 'Clear', exact: true })).toBeDisabled()
})
