import {describe,it,expect,vi} from 'vitest'
import {getStats,recordStart,recordFinish} from '../src/game/analytics'
import {RoundClock} from '../src/game/roundClock'
import {advanceSky,boardOver,canSlide,computerMove,lines,makeMaze,makeSky,makeWords,mazeMove,mazePath,memoryDeal,memoryFlip,mergeLine,newMerge,newOrbit,placeMark,popOrbit,seeded,selectedWord,shuffle,skyJump,skyLane,slideBoard,spaceWords,spawnTile,wordSelection,winner,type Direction,type Mark} from '../src/game/logic'

describe('maze generation and wall-safe navigation',()=>{
  it('500 seeds are connected, bounded, solvable mazes',()=>{for(let seed=0;seed<500;seed++){const maze=makeMaze(5,seeded(seed)),goal={x:9,y:9};expect(maze).toHaveLength(11);expect(maze[0]!.every(Boolean)&&maze[10]!.every(Boolean)).toBe(true);expect(maze.every(row=>row[0]&&row[10])).toBe(true);const path=mazePath(maze,{x:1,y:1},goal);expect(path.at(-1)).toEqual(goal);for(let i=1;i<path.length;i++){const a=path[i-1]!,b=path[i]!;expect(Math.abs(a.x-b.x)+Math.abs(a.y-b.y)).toBe(1);expect(maze[b.y]![b.x]).toBe(false)}for(let y=1;y<10;y+=2)for(let x=1;x<10;x+=2)expect(mazePath(maze,{x:1,y:1},{x,y}).length).toBeGreaterThan(0)}})
  it('blocks outer walls and moves exactly one tile',()=>{const maze=makeMaze(5,seeded(4)),at={x:1,y:1};expect(mazeMove(maze,at,'up')).toEqual(at);expect(mazeMove(maze,at,'left')).toEqual(at);for(const d of ['up','down','left','right']as Direction[]){const next=mazeMove(maze,at,d);expect(Math.abs(next.x-at.x)+Math.abs(next.y-at.y)).toBeLessThanOrEqual(1)}})
})
describe('memory',()=>{
  it('100 deals contain exactly six pairs with unbiased shuffle semantics',()=>{for(let n=0;n<100;n++){const state=memoryDeal(seeded(n));expect(state.deck).toHaveLength(12);expect(new Set(state.deck).size).toBe(6);for(const k of new Set(state.deck))expect(state.deck.filter(x=>x===k)).toHaveLength(2)}})
  it('rejects duplicate taps, third taps and matched cards',()=>{let s=memoryDeal(seeded(4));s=memoryFlip(s,0);expect(memoryFlip(s,0)).toBe(s);const different=s.deck.findIndex(k=>k!==s.deck[0]);s=memoryFlip(s,different);expect(s.open).toHaveLength(2);expect(memoryFlip(s,4)).toBe(s);s={...s,open:[]};s=memoryFlip(s,0);s=memoryFlip(s,s.deck.findIndex((k,i)=>i!==0&&k===s.deck[0]));expect(s.matched).toHaveLength(2);expect(memoryFlip(s,0)).toBe(s)})
  it('finishes only after every pair is matched',()=>{let s=memoryDeal();for(const k of new Set(s.deck)){const indices=s.deck.map((v,i)=>v===k?i:-1).filter(i=>i>=0);s=memoryFlip(memoryFlip(s,indices[0]!),indices[1]!)}expect(s.matched).toHaveLength(12);expect(new Set(s.matched).size).toBe(12);expect(s.turns).toBe(6)})
})
describe('three in a row',()=>{
  it.each(lines)('detects winning line %s %s %s',(a,b,c)=>{for(const mark of ['X','O']as const){const b2:Mark[]=Array(9).fill(null);b2[a]=b2[b]=b2[c]=mark;expect(winner(b2)).toBe(mark);expect(computerMove(b2)).toBeNull();expect(placeMark(b2,8,mark)).toBe(b2)}})
  it('takes a win at index zero and blocks a human win',()=>{expect(computerMove([null,'O','O','X',null,'X',null,null,null])).toBe(0);expect(computerMove(['X','X',null,null,'O',null,null,null,null])).toBe(2)})
  it('detects full draw and refuses overwrite',()=>{const draw:Mark[]=['X','O','X','X','O','O','O','X','X'];expect(winner(draw)).toBeNull();expect(boardOver(draw)).toBe(true);expect(computerMove(draw)).toBeNull();expect(placeMark(draw,0,'O')).toBe(draw)})
  it('computer always makes a legal move across every reachable nonterminal board',()=>{const seen=new Set<string>();function visit(board:Mark[],turn:'X'|'O'){const key=board.join('-');if(seen.has(key)||boardOver(board))return;seen.add(key);const move=computerMove(board,seeded(2));expect(move).not.toBeNull();expect(board[move!]).toBeNull();for(let i=0;i<9;i++)if(!board[i])visit(placeMark(board,i,turn),turn==='X'?'O':'X')}visit(Array(9).fill(null),'X');expect(seen.size).toBeGreaterThan(4000)})
})
describe('merge rules',()=>{
  it.each([[[2,2,2,2],[4,4,0,0],8],[[4,4,8,0],[8,8,0,0],8],[[2,0,2,4],[4,4,0,0],4],[[4,0,0,4],[8,0,0,0],8],[[0,0,0,0],[0,0,0,0],0]])('merges a tile only once: %j',(input,output,score)=>{const result=mergeLine(input as number[]);expect(result.line).toEqual(output);expect(result.score).toBe(score)})
  it('slides in all four directions without spawning or losing value',()=>{for(let seed=0;seed<300;seed++){const rng=seeded(seed),board=Array.from({length:16},()=>rng()<.4?0:2**(1+Math.floor(rng()*5)));for(const d of ['up','down','left','right']as Direction[]){const r=slideBoard(board,d);expect(r.board.reduce((a,b)=>a+b,0)).toBe(board.reduce((a,b)=>a+b,0));expect(r.board).toHaveLength(16);expect(r.moved).toBe(r.board.some((n,i)=>n!==board[i]))}}})
  it('respects orientation and leaves invalid moves unchanged',()=>{const board=[2,2,0,0,...Array(12).fill(0)];expect(slideBoard(board,'right').board.slice(0,4)).toEqual([0,0,0,4]);expect(slideBoard(board,'down').board.slice(12)).toEqual([2,2,0,0]);const left=slideBoard(board,'left').board;expect(slideBoard(left,'left').moved).toBe(false)})
  it('spawns on an empty cell only and recognizes no-move boards',()=>{for(let s=0;s<50;s++){const board=newMerge(seeded(s));expect(board.filter(Boolean)).toHaveLength(2);const next=spawnTile(board,seeded(s));expect(next.filter(Boolean)).toHaveLength(3)}const full=[2,4,2,4,4,2,4,2,2,4,2,4,4,2,4,2];expect(canSlide(full)).toBe(false);expect(spawnTile(full)).toBe(full);expect(canSlide([2,2,...full.slice(2)])).toBe(true)})
})
describe('word search',()=>{
  it('500 boards contain all promised words, including reverse selection',()=>{for(let s=0;s<500;s++){const puzzle=makeWords(seeded(s));expect(puzzle.letters).toHaveLength(49);expect(puzzle.letters.every(l=>/^[A-Z]$/.test(l))).toBe(true);for(const word of spaceWords){const cells=puzzle.placements[word]!;expect(cells.map(i=>puzzle.letters[i]).join('')).toBe(word);expect(selectedWord(puzzle,cells[0]!,cells.at(-1)!)).toBe(word);expect(selectedWord(puzzle,cells.at(-1)!,cells[0]!)).toBe(word)}}})
  it('rejects non-straight, out-of-bounds and bent selections',()=>{const p=makeWords();expect(wordSelection(p,0,9)).toEqual([]);expect(wordSelection(p,-1,9)).toEqual([]);expect(wordSelection(p,0,50)).toEqual([]);expect(selectedWord(p,0,0)).toBeNull()})
})
describe('Sky Dash',()=>{
  it('generates enough track, leaves escape lanes, and clamps steering',()=>{for(let i=0;i<50;i++){const s=makeSky(seeded(i));expect(s.items.at(-1)!.distance).toBeGreaterThan(750);expect(new Set(s.items.map(x=>x.id)).size).toBe(s.items.length);for(const item of s.items.filter(x=>x.kind==='block'))expect(s.items.find(x=>x.distance===item.distance&&x.kind==='gem')!.lane).not.toBe(item.lane)}let s=makeSky();for(let i=0;i<10;i++)s=skyLane(s,1);expect(s.lane).toBe(1);for(let i=0;i<10;i++)s=skyLane(s,-1);expect(s.lane).toBe(-1)})
  it('collects only crossed items in the occupied lane, once',()=>{let s={...makeSky(),items:[{id:1,lane:0,distance:1,kind:'gem' as const,hit:false},{id:2,lane:1,distance:1,kind:'gem' as const,hit:false}]};s=advanceSky(s,.2);expect(s.gems).toBe(1);expect(s.score).toBe(10);s=advanceSky(s,.2);expect(s.gems).toBe(1)})
  it('collision does not end the ride or remove points, and jumping avoids it',()=>{const base={...makeSky(),score:40,combo:4,items:[{id:1,lane:0,distance:2,kind:'block' as const,hit:false}]};const bumped=advanceSky(base,.3);expect(bumped.bumps).toBe(1);expect(bumped.score).toBe(40);expect(bumped.combo).toBe(0);expect(advanceSky(skyJump(base),.3).bumps).toBe(0);expect(skyJump(skyJump(base)).cooldown).toBe(1.15)})
  it('has frame-rate-independent distance and collision counts',()=>{let a=makeSky(seeded(4)),b=makeSky(seeded(4));for(let n=0;n<750;n++)a=advanceSky(a,.1);for(let n=0;n<4500;n++)b=advanceSky(b,1/60);expect(a.distance).toBeCloseTo(b.distance,6);expect(a.gems).toBe(b.gems);expect(a.bumps).toBe(b.bumps);expect(a.score).toBe(b.score)})
  it('ignores invalid time and never permits negative jump timers',()=>{const s=makeSky();expect(advanceSky(s,-1)).toBe(s);expect(advanceSky(s,NaN)).toBe(s);const jumped=advanceSky(skyJump(s),2);expect(jumped.air).toBe(0);expect(jumped.cooldown).toBe(0)})
})
describe('Orbit Pop',()=>{
  it('awards an optional bonus only for the spotlighted planet',()=>{const s=newOrbit();expect(popOrbit(s,2,0).bonus).toBe(1);expect(popOrbit(s,1,0).bonus).toBe(0)})
  it('rejects stale target IDs, double taps and stops at 18',()=>{let s=newOrbit();s=popOrbit(s,0,0);expect(s.popped).toBe(1);expect(popOrbit(s,0,200)).toBe(s);expect(popOrbit(s,1,100)).toBe(s);for(let n=1;n<18;n++){s=popOrbit(s,s.slots[n%6]!,n*200);expect(new Set(s.slots).size).toBe(6)}expect(s.popped).toBe(18);expect(popOrbit(s,s.slots[0]!,5000)).toBe(s)})
})
describe('short-session clock',()=>{
  it('repairs malformed device counters and tolerates blocked storage',()=>{let value=JSON.stringify({version:1,sessions:'bad',games:{sky:{starts:-5,seconds:'no',finishes:NaN}}});vi.stubGlobal('localStorage',{getItem:()=>value,setItem:(_k:string,v:string)=>{value=v}});expect(getStats().sessions).toBe(0);recordStart('sky');recordFinish('sky');expect(getStats().games.sky).toEqual({starts:1,seconds:0,finishes:1});vi.stubGlobal('localStorage',{getItem:()=>{throw Error('blocked')},setItem:()=>{throw Error('blocked')}});expect(()=>recordStart('sky')).not.toThrow();vi.unstubAllGlobals()})
  it('does not run before start and excludes all paused time',()=>{const c=new RoundClock(75000);expect(c.tick(10000)).toBe(0);c.resume(10000);c.tick(20000);c.pause(25000);expect(c.elapsed).toBe(15000);c.tick(100000);expect(c.elapsed).toBe(15000);c.resume(100000);c.tick(110000);expect(c.elapsed).toBe(25000)})
  it('caps a throttled tick at the exact end and never goes negative',()=>{const c=new RoundClock(60000);c.resume(0);c.tick(180000);expect(c.elapsed).toBe(60000);expect(c.done).toBe(true);c.pause(180000);c.tick(999999);expect(c.elapsed).toBe(60000)})
  it('shuffle preserves inputs',()=>{const input=[1,2,3,4];expect(shuffle(input,seeded(2)).sort()).toEqual(input);expect(input).toEqual([1,2,3,4])})
})
