import { useState } from 'react'
import { makeWords, selectedWord, spaceWords, wordSelection } from '../logic'
import { useGame } from '../useGame'
import { Icon } from '../Icons'
import { playCue } from '../sound'
export function Words(){
  const {paused,finish}=useGame(),[puzzle]=useState(()=>makeWords()),[start,setStart]=useState<number|null>(null),[found,setFound]=useState<string[]>([]),[highlight,setHighlight]=useState<number[]>([]),[hint,setHint]=useState<number|null>(null),[message,setMessage]=useState('Tap the first and last letter of a word.')
  const select=(index:number)=>{if(paused)return;if(start===null){setStart(index);setHint(null);setMessage('Now tap the last letter.');return}const word=selectedWord(puzzle,start,index);if(word&&!found.includes(word)){const next=[...found,word];setFound(next);setHighlight(old=>[...old,...wordSelection(puzzle,start,index)]);setMessage(`${word} found. Nice spotting.`);playCue('match');if(next.length===spaceWords.length)finish('Every word found. Stellar spotting.')}else setMessage(word?'You already found that one.':'Try another line. Words go straight.');setStart(null)}
  return <div className="puzzle-area"><div className="word-list" aria-label="Words to find">{spaceWords.map(word=><span className={found.includes(word)?'found':''} key={word}>{found.includes(word)&&<Icon name="check" size={16}/>} {word}</span>)}</div><div className="word-board" role="group" aria-label="Word search grid">{puzzle.letters.map((letter,i)=><button key={i} className={`${highlight.includes(i)?'found':''} ${i===start?'selected':''} ${i===hint?'hint':''}`} aria-label={`Row ${Math.floor(i/puzzle.size)+1} column ${i%puzzle.size+1}: ${letter}`} aria-pressed={start===i} onClick={()=>select(i)}>{letter}</button>)}</div><p className="control-note" aria-live="polite">{message}</p><div className="word-actions"><button className="secondary-button" onClick={()=>{const word=spaceWords.find(w=>!found.includes(w));if(word){setHint(puzzle.placements[word]![0]!);setMessage(`The highlighted letter starts ${word}.`)}}}><Icon name="sparkle"/> Hint</button><button className="text-button" disabled={start===null} onClick={()=>{setStart(null);setMessage('Tap the first and last letter of a word.')}}>Clear selection</button></div></div>
}
